import type { Metadata } from "next";
import { Teko } from "next/font/google";
import "./ui/globals.css";

const teko = Teko({
  weight: ["400", '300', "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${teko.className} antialiased p-4`}
      >
        {children}
      </body>
    </html>
  );
}
